### PR TITLE
Added linter and fixed all TS style issues

### PR DESCRIPTION
**Pull request by sbbowers**

### CODE REVIEW

**Comment by marcj** [comment]
Whats the reason of `"` over `'`?

**Comment by sbbowers** [comment]
I'm not a typescript expert. The linter just complains:

> (quotemark) WebStorage.ts[23, 26]: ' should be "

The style guideline says to use double quotes for strings, but doesn't really give a reason.

**Comment by sbbowers** [comment]
I also added a new NPM version, which I recommend publishing, or at least doing a new release from master because your current 0.3.0 release doesn't compile.

**Comment by sbbowers** [comment]
Marc, is there something I need to modify to get this accepted, or just rejected?

**Comment by marcj** [comment]
Nothing, anything good. thanks :)

**Pull request merged**
